const generate = require('./lib/generate');
const order = require('@chancedigital/css-property-sort-order-smacss');
const sortOrderRules = generate(order);

module.exports = {
  plugins: ['stylelint-order'],
  rules: {
    'at-rule-name-case': 'lower',
    'at-rule-no-unknown': null,
    'block-no-empty': true,
    'color-no-invalid-hex': true,
    'declaration-block-no-duplicate-properties': [
      true,
      {
        ignore: ['consecutive-duplicates-with-different-values'],
      },
    ],
    'declaration-block-no-shorthand-property-overrides': true,
    'font-family-no-duplicate-names': true,
    'font-family-no-missing-generic-family-keyword': true,
    'function-linear-gradient-no-nonstandard-direction': true,
    'keyframe-declaration-no-important': true,
    'length-zero-no-unit': true,
    'max-empty-lines': 2,
    'max-line-length': [120, { ignore: ['non-comments'] }],
    'max-nesting-depth': 6,
    'media-feature-name-case': 'lower',
    'media-feature-name-no-unknown': true,
    'no-descending-specificity': [true, { ignore: ['selectors-within-list'] }],
    'no-duplicate-at-import-rules': true,
    'no-duplicate-selectors': true,
    'no-empty-source': true,
    'no-extra-semicolons': true,
    'number-leading-zero': 'always',
    'number-no-trailing-zeros': true,
    'property-no-unknown': [
      true,
      { ignoreProperties: ['font-smoothing', 'font-smooth', 'initial-letter'] },
    ],
    'selector-attribute-quotes': 'always',
    'selector-max-compound-selectors': 6,
    'selector-max-id': 0,
    'selector-max-type': 4,
    'selector-pseudo-class-case': 'lower',
    'selector-pseudo-class-no-unknown': true,
    'selector-pseudo-element-no-unknown': true,
    'selector-type-no-unknown': true,
    'unit-case': 'lower',
    'at-rule-no-vendor-prefix': true,
    'media-feature-name-no-vendor-prefix': true,
    'property-no-vendor-prefix': true,
    'unit-no-unknown': true,
    'value-no-vendor-prefix': true,
    'order/properties-order': sortOrderRules,
  },
};
