module.exports = {
  extends: '../index.js',
  rules: {
    'at-rule-name-space-after': 'always-single-line',
    'declaration-bang-space-after': 'never',
    'declaration-bang-space-before': 'always',
    'declaration-colon-space-after': 'always-single-line',
    'declaration-colon-space-before': 'never',
    'declaration-empty-line-before': [
      'never',
      {
        ignore: ['after-comment', 'first-nested'],
      },
    ],
    'function-calc-no-unspaced-operator': true,
    'function-parentheses-space-inside': 'always-single-line',
    'media-feature-colon-space-after': 'always',
    'media-feature-colon-space-before': 'never',
    'media-feature-parentheses-space-inside': 'always',
    'media-feature-range-operator-space-after': 'always',
    'media-feature-range-operator-space-before': 'always',
    'media-query-list-comma-newline-before': 'never-multi-line',
    'media-query-list-comma-space-after': 'always-single-line',
    'selector-attribute-operator-space-after': 'never',
    'selector-attribute-operator-space-before': 'never',
    'selector-list-comma-newline-after': 'always',
    'selector-list-comma-newline-before': 'never-multi-line',
    'selector-list-comma-space-after': 'always-single-line',
    'selector-list-comma-space-before': 'never',
    'selector-pseudo-class-parentheses-space-inside': 'always',
    'string-no-newline': true,
    'string-quotes': 'double',
    indentation: ['tab', { ignore: ['value', 'param'] }],
  },
};
